// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: idl/replay.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId  int64  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	OldReq  []byte `protobuf:"bytes,2,opt,name=old_req,json=oldReq,proto3" json:"old_req,omitempty"`
	OldResp []byte `protobuf:"bytes,3,opt,name=old_resp,json=oldResp,proto3" json:"old_resp,omitempty"`
	NewResp []byte `protobuf:"bytes,4,opt,name=new_resp,json=newResp,proto3" json:"new_resp,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_replay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_idl_replay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_idl_replay_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Record) GetOldReq() []byte {
	if x != nil {
		return x.OldReq
	}
	return nil
}

func (x *Record) GetOldResp() []byte {
	if x != nil {
		return x.OldResp
	}
	return nil
}

func (x *Record) GetNewResp() []byte {
	if x != nil {
		return x.NewResp
	}
	return nil
}

type AddRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *AddRecordReq) Reset() {
	*x = AddRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_replay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordReq) ProtoMessage() {}

func (x *AddRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_replay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordReq.ProtoReflect.Descriptor instead.
func (*AddRecordReq) Descriptor() ([]byte, []int) {
	return file_idl_replay_proto_rawDescGZIP(), []int{1}
}

func (x *AddRecordReq) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type AddRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AddRecordResp) Reset() {
	*x = AddRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_replay_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordResp) ProtoMessage() {}

func (x *AddRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_replay_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordResp.ProtoReflect.Descriptor instead.
func (*AddRecordResp) Descriptor() ([]byte, []int) {
	return file_idl_replay_proto_rawDescGZIP(), []int{2}
}

func (x *AddRecordResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddRecordResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_idl_replay_proto protoreflect.FileDescriptor

var file_idl_replay_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x64, 0x6c, 0x2f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x70, 0x0a, 0x06, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x6f, 0x6c, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x6f, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x6c, 0x64, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6f, 0x6c, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x22, 0x36, 0x0a, 0x0c,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x06,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72,
	0x65, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x22, 0x35, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_replay_proto_rawDescOnce sync.Once
	file_idl_replay_proto_rawDescData = file_idl_replay_proto_rawDesc
)

func file_idl_replay_proto_rawDescGZIP() []byte {
	file_idl_replay_proto_rawDescOnce.Do(func() {
		file_idl_replay_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_replay_proto_rawDescData)
	})
	return file_idl_replay_proto_rawDescData
}

var file_idl_replay_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_idl_replay_proto_goTypes = []interface{}{
	(*Record)(nil),        // 0: replay.Record
	(*AddRecordReq)(nil),  // 1: replay.AddRecordReq
	(*AddRecordResp)(nil), // 2: replay.AddRecordResp
}
var file_idl_replay_proto_depIdxs = []int32{
	0, // 0: replay.AddRecordReq.record:type_name -> replay.Record
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_replay_proto_init() }
func file_idl_replay_proto_init() {
	if File_idl_replay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_replay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_replay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_replay_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_replay_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idl_replay_proto_goTypes,
		DependencyIndexes: file_idl_replay_proto_depIdxs,
		MessageInfos:      file_idl_replay_proto_msgTypes,
	}.Build()
	File_idl_replay_proto = out.File
	file_idl_replay_proto_rawDesc = nil
	file_idl_replay_proto_goTypes = nil
	file_idl_replay_proto_depIdxs = nil
}
